<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$player = Session::get("player");

if(Session::has("dados")){
    $dados = Session::get("dados");
    $dice0 = 'Game/Dice/'.(string)$dados[0].'.png';
    $dice1 = 'Game/Dice/'.(string)$dados[1].'.png';
}
else{
    $dice0 = "Game/Dice/1.png";
    $dice1 = "Game/Dice/1.png";
}

if(Session::has("podeLancarDados")) {
    $podeLancarDados = Session::get("podeLancarDados");
    echo $podeLancarDados;
}

if(Session::has("selectedNums")){
    $selectedNums = Session::get("selectedNums");
}
else{
    $selectedNums = array();
}

if(Session::has("playerNums")){
    $playerNums = Session::get("playerNums");
}
else{
    $playerNums = array();
}

$cpuTurn = Session::get("cpuTurn");
if($cpuTurn){
    $cpuPlays = Session::get("cpuPlays");
}
else{
    $cpuPlays = array();
}
$PlayerScore = Session::get("PlayerScore");
$CpuScore = Session::get("CpuScore");
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap4.min.css')?>" media="screen" >
    <title>Game</title>
</head>
<style>
    html, body{
        background-image: linear-gradient(to right bottom, #a741ff, #9157fc, #7e65f6, #6f70ed, #6678e2, #4a88ea, #2a97ee, #00a4ef, #00befa, #00d6f8, #00ecea, #00ffd4);
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .middleButtons{
        margin-top: 250px;
    }

    .lancarBtn{
        background: #00ffd4;
        font-size: 1.6rem;
    }

    .points{
        background-color: #7e65f6;
        text-align: center;
        padding-top: .2rem;
        padding-bottom: .05rem;
        margin: auto auto auto 5px;
        border-radius: 12px;
    }

    .dados{
        height: 64px;
        width: 64px;
        border-radius: 12px;
        margin:auto;
    }

    .btn-number{
        background: #00ffd4;
        text-align: center;
        padding-top: .2rem;
        padding-bottom: .05rem;
        margin: auto auto 25px 5px;
        border-radius: 12px;
        cursor: pointer;
    }

    <?php
    if(isset($dados)){
    ?>
    .btn-number:hover{
        background: #7bf8e0;
    }
    .btn-number:active{
        background: #4acbaf;
    }
    <?php
    }
    ?>

    .disabled{
        background: rgba(0, 255, 212, 0.49);
    }
    .disabled:hover{
        background: rgba(0, 255, 212, 0.49);
    }
    .disabled:active{
        background: rgba(0, 255, 212, 0.49);
    }
    .gameBoard{
        height: 800px;
        width: 500px;
        background-color: #252525;
        border-radius: 25px;
    }

    .leftSide{
        margin: auto;
        margin-top: 5%;
        height: 90%;
    }

    .middle{
        margin: auto;
        margin-top: 5%;
        width: 40%;
        height: 90%;
    }

    .rightSide{
        margin: auto;
        margin-top: 5%;
        height: 90%;
    }
</style>
<body>
<div class="text-center mt-5 mb-5">
    <h1> <?php echo $player->username ?> vs CPU</h1>
    <br>
    <a href="<?= URL::toRoute('game/giveup')?>"><button class="btn btn-dark">Give up</button></a>
</div>
<br>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="container gameBoard">
                <div class="row gameBoard">

                    <div class="leftSide col-3">
                        <div class="container">
                            <?php
                            for($i = 1; $i < 10; $i++)
                            {
                                ?>
                                <div class="row">
                                    <div class="col-12">
                                        <a <?php if(isset($dados) && !in_array($i, $playerNums)) echo 'href="select/'.$i.'"' ?>"><div class=" <?php if(in_array($i, $selectedNums) || in_array($i, $playerNums)) echo "disabled" ?>  btn-number btnPlayer1 <?php echo $i ?>"><h1><?php echo $i ?></h1></div></a>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>

                    <div class="middle col-6">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col">
                                    <div class="points" id="Player1Points"><h1><?php echo $PlayerScore ?></h1></div>c
                                </div>
                                <div class="col">
                                    <div class="points" id="Player2Points"><h1><?php echo $CpuScore ?></h1></div>
                                </div>
                            </div>
                            <div class="row justify-content-center middleButtons">
                                <a <?php if($podeLancarDados){?> href="<?= URL::toRoute('game/lancarDados') ?>" <?php }?><button class=" <?php if(!$podeLancarDados) echo "disabled "; ?>btn lancarBtn" id="btnLancarDados"><b>Throw Dice</b></button></a>
                            </div>
                            <br>
                            <div class="row justify-content-center">
                                <div class="col">
                                    <div class="dados" id="dado1"><h1><img src="<?= Asset::image($dice0) ?>" height="64px"></h1></div>c
                                </div>
                                <div class="col">
                                    <div class="dados" id="dado2"><h1><img src="<?= Asset::image($dice1) ?>" height="64px"></h1></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="rightSide col-3">
                        <div class="container">
                            <?php
                            for($i = 1; $i < 10; $i++)
                            {
                                ?>
                                <div class="row">
                                    <div class="col-12">
                                        <div class=" <?php if(in_array($i, $cpuPlays)) echo "disabled" ?> btn-number btnPlayer2 <?php echo $i ?>"><h1><?php echo $i ?></h1></div>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>