<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

$player = Session::get("player");
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap4.min.css')?>" media="screen" >
    <title>Game</title>
    <script src="<?= Asset::js('/jquery.js')?>"></script>
</head>
<style>
    html, body{
        background-image: linear-gradient(to right bottom, #a741ff, #9157fc, #7e65f6, #6f70ed, #6678e2, #4a88ea, #2a97ee, #00a4ef, #00befa, #00d6f8, #00ecea, #00ffd4);
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .middleButtons{
        margin-top: 250px;
    }

    .lancarBtn{
        background: #00ffd4;
        font-size: 1.6rem;
    }

    .points{
        background-color: #7e65f6;
        text-align: center;
        padding-top: .2rem;
        padding-bottom: .05rem;
        margin: auto auto auto 5px;
        border-radius: 12px;
    }

    .dados{
        background-color: #7e65f6;
        text-align: center;
        padding-top: .2rem;
        padding-bottom: .05rem;
        margin: ;
        border-radius: 12px;
    }

    .btn-number{
        background: #00ffd4;
        text-align: center;
        padding-top: .2rem;
        padding-bottom: .05rem;
        margin: auto auto 25px 5px;
        border-radius: 12px;
        cursor: pointer;
    }

    .btn-number:hover{
        background: #7bf8e0;
    }

    .btn-number:active{
        background: #4acbaf;
    }

    .gameBoard{
        height: 800px;
        width: 500px;
        background-color: #252525;
        border-radius: 25px;
    }

    .leftSide{
        margin: auto;
        margin-top: 5%;
        height: 90%;
    }

    .middle{
        margin: auto;
        margin-top: 5%;
        width: 40%;
        height: 90%;
    }

    .rightSide{
        margin: auto;
        margin-top: 5%;
        height: 90%;
    }
</style>
<body>
<div class="text-center mt-5 mb-5">
    <h1> <?php echo $player->username ?> vs CPU</h1>
    <br>
</div>
<br>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="container gameBoard">
                <div class="row gameBoard">

                    <div class="leftSide col-3">
                        <div class="container">
                            <?php
                            for($i = 1; $i < 10; $i++)
                            {
                                ?>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="btn-number btnPlayer1 <?php echo $i ?>"><h1><?php echo $i ?></h1></div>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>

                    <div class="middle col-6">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col">
                                    <div class="points" id="Player1Points"><h1>0</h1></div>c
                                </div>
                                <div class="col">
                                    <div class="points" id="Player2Points"><h1>0</h1></div>
                                </div>
                            </div>
                            <div class="row justify-content-center middleButtons">
                                <button class="btn lancarBtn" id="btnLancarDados"><b>Lançar Dados</b></button>
                            </div>
                            <br>
                            <div class="row justify-content-center">
                                <div class="col">
                                    <div class="dados" id="dado1"><h1><img src="" height="64px"></h1></div>c
                                </div>
                                <div class="col">
                                    <div class="dados" id="dado2"><h1><img src="" height="64px"></h1></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="rightSide col-3">
                        <div class="container">
                            <?php
                            for($i = 1; $i < 10; $i++)
                            {
                                ?>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="btn-number btnPlayer2 <?php echo $i ?>"><h1><?php echo $i ?></h1></div>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</body>
<script>
    $(document).ready(function () {
        $('#btnLancarDados').click(function(){
            var num1, num2;
            num1= getDado();
            num2 = getDado;
            console.log(num1 + " " + num2);
        })
        
        function getDado(){
            $.ajax({
                type: "post",
                url: "<?= URL::toRoute('gameLogic/lancarDados')?>",
                success: function (response) {
                    return response;
                }
            });
        }
    });
</script>
</html>