<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$player = Session::get("player");
$games = Data::get("games");
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap4.min.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/game.css')?>" media="screen" >
    <title>Main Menu</title>
</head>
<body>
<div class="container main">
    <div class="row justify-content-center">
        <div class="col">
            <div id="matchHistory" class="box text-center pt-3 pb-5">
                <h1>Match History</h1>
                <br>
                <?php
                if($games != null){
                ?>
                    <table class="table table-dark table-striped">
                        <thead>
                            <th>Data</th>
                            <th>Resultado</th>
                        </thead>
                        <tbody>
                            <tr>
                                <?php
                                foreach($games as $game)
                                {
                                ?>
                                <td><?php echo $game->datahora ?></td>
                                <td><?php echo $game->resultado ?></td>
                                <?php
                                }
                                ?>
                            </tr>
                <?php
                }
                else{
                    ?>
                    <h4>There is no game records to show</h4>
                    <?php
                }
                ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mt-5">
            <div class="container">
                <div class="row justify-content-center">
                    <form method="post" action="game">
                    <input type="submit" class="btn btn-dark" value="Start Game">
                    </form>
                </div>
                <br>
                <div class="row justify-content-center">
                    <form method="post" action="<?= URL::toRoute('game/logout')?>">
                        <input type="submit" class="btn btn-dark" value="Logout">
                    </form>
                </div>
            </div>
        </div>
        <div class="col">
            <div id="PlayerInfo" class="box pt-5 pl-5 pr-5 pb-3">
                <label>Name:</label>
                <span><?php echo $player->nomecompleto ?></span>
                <br>
                <label>Birth Date:</label>
                <span><?php echo $player->datanascimento ?></span>
                <br>
                <label>Email:</label>
                <span><?php echo $player->email ?></span>
                <br>
                <label>Permissions:</label>
                <span><?php echo $player->isadmin ? 'Administrator' : 'Jogador' ?></span>
                <br>
                <br>
                <?php
                if($player->isadmin){
                    ?>
                    <a href="<?= URL::toRoute('game/backoffice')?>"><button class="btn btn-dark">Administration</button></a>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>
</body>
</html>