<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap4.min.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/game.css')?>" media="screen" >
    <title>Login</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div id="loginBox">
                <form method="post" action="<?= URL::toRoute('game/authenticate')?>">
                    <div class="container">
                        <br>
                        <div class="row text-center">
                            <div class="col">
                                <h1>Login</h1>
                            </div>
                        </div>
                        <br>
                        <div class="row justify-content-center">
                            <div class="col-9 mt-5">
                                <label for="username">Username:</label>
                                <input type="text" name="username" class="form-control">
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-9 mt-5">
                                <label for="password">Password:</label>
                                <input type="password" name="password" class="form-control">
                                <br>
                                <span>Click <a href="<?= URL::toRoute('game/register')?>">here</a> to register!</span>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-5 mt-5">
                                <input type="submit" value="Entrar" class="form-control btn btn-dark">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>