<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
$games = Data::get('games');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap4.min.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/game.css')?>" media="screen" >
    <title>Backoffice</title>
</head>
<body>
<div class="container main">
    <div class="row justify-content-center">
        <div class="col">
            <div id="top10" class="box text-center pt-3 pb-5">
                <h1>Top10</h1>
                <br>
                <table class="table table-dark table-striped">
                    <thead>
                        <th>Full Name</th>
                        <th>Victories</th>
                    </thead>
                    <tbody>
                    <?php
                        foreach($games as $game)
                        {
                        ?>
                            <tr>
                                <td><?php echo $game->username ?></td>
                                <td><?php echo $game->victories ?></td>
                            </tr>
                        <?php
                        }
                    ?>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>
</body>
</html>